### PR TITLE
Various fixes / improvements

### PR DESCRIPTION
**Pull request by appgurueu**
- Making Luacheck happy
- `core.string_to_pos` cleanup (unrelated, but feels nice)
- Less permissive area parsing by anchoring the patterns
- Rewriting the tests as busted tests (+ some adding & grouping)
- Various minor pattern tweaks

### CODE REVIEW

**Comment by Wuzzy2** [comment]
```
 	local x, y, z = value:trim():match("^([%d.-]+)[,%s]%s*([%d.-]+)[,%s]%s*([%d.-]+)$") 
```

This smells like a potential crasher because `string.match` can return `nil`.

**Comment by appgurueu** [comment]
> This smells like a potential crasher because `string.match` can return `nil`.

Why would this crash anything though? If `string.match` returns nothing, `x`, `y` and `z` will be `nil` and the subsequent `if` won't trigger so the fallthrough `return nil` will be executed.

**Comment by Wuzzy2** [comment]
No, wait. Forget what I said. I read it the wrong way. I had a brainfart, sorry. I will test this eventually.

**Comment by Wuzzy2** [comment]
This test fails:

* `/time ~-0:05: Go back in time by 5 minutes`

**Comment by appgurueu** [comment]
> This test fails:
> 
>     * `/time ~-0:05: Go back in time by 5 minutes`

Hmm, I don't think I have touched that but I'll try to fix it.

**Comment by appgurueu** [comment]
The issue was comparing the hours against zero rather than using pattern matching, which failed if the hours were zero.

**Pull request merged**
